export const seed = [
  {
    name: "Camiseta Deportiva",
    price: 19.99,
    category: "Ropa",
    description: "Camiseta de alta calidad para deportes al aire libre.",
    stock: 50,
  },
  {
    name: "Auriculares Bluetooth",
    price: 29.99,
    category: "Electrónica",
    description: "Auriculares inalámbricos con excelente calidad de sonido.",
    stock: 150,
  },
  {
    name: "Botella de Agua Reutilizable",
    price: 12.49,
    category: "Accesorios",
    description:
      "Botella de agua de acero inoxidable, mantiene las bebidas frías por 24 horas.",
    stock: 75,
  },
  {
    name: "Mochila de Viaje",
    price: 49.99,
    category: "Viaje",
    description: "Mochila resistente al agua con múltiples compartimentos.",
    stock: 30,
  },
  {
    name: "Zapatillas de Running",
    price: 69.99,
    category: "Calzado",
    description: "Zapatillas ligeras y cómodas para correr largas distancias.",
    stock: 40,
  },
  {
    name: "Reloj Inteligente",
    price: 99.99,
    category: "Electrónica",
    description:
      "Reloj inteligente con monitor de actividad física y notificaciones.",
    stock: 60,
  },
  {
    name: "Lámpara de Escritorio LED",
    price: 24.99,
    category: "Hogar",
    description: "Lámpara de escritorio con luz ajustable y puerto USB.",
    stock: 80,
  },
  {
    name: "Cafetera de Goteo",
    price: 39.99,
    category: "Electrodomésticos",
    description:
      "Cafetera de goteo con capacidad para 12 tazas y función de apagado automático.",
    stock: 100,
  },
  {
    name: "Juego de Sábanas de Microfibra",
    price: 34.99,
    category: "Hogar",
    description:
      "Juego de sábanas de microfibra suave y duradera para camas queen.",
    stock: 25,
  },
  {
    name: "Gafas de Sol Polarizadas",
    price: 14.99,
    category: "Accesorios",
    description: "Gafas de sol polarizadas con protección UV400.",
    stock: 120,
  },
  {
    name: "Teclado Mecánico",
    price: 89.99,
    category: "Electrónica",
    description: "Teclado mecánico RGB con interruptores de alta durabilidad.",
    stock: 45,
  },
  {
    name: "Silla Ergonómica de Oficina",
    price: 199.99,
    category: "Muebles",
    description: "Silla de oficina ergonómica con soporte lumbar ajustable.",
    stock: 15,
  },
  {
    name: "Libro: El Alquimista",
    price: 9.99,
    category: "Libros",
    description: "Novela inspiradora escrita por Paulo Coelho.",
    stock: 200,
  },
  {
    name: "Cámara de Seguridad para el Hogar",
    price: 49.99,
    category: "Seguridad",
    description:
      "Cámara de seguridad WiFi con visión nocturna y detección de movimiento.",
    stock: 65,
  },
  {
    name: "Cinturón de Cuero",
    price: 19.99,
    category: "Moda",
    description: "Cinturón de cuero genuino con hebilla de acero inoxidable.",
    stock: 75,
  },
  {
    name: "Parlante Bluetooth Portátil",
    price: 34.99,
    category: "Electrónica",
    description: "Parlante portátil resistente al agua con sonido estéreo.",
    stock: 90,
  },
  {
    name: "Bicicleta de Montaña",
    price: 299.99,
    category: "Deportes",
    description:
      "Bicicleta de montaña con suspensión delantera y frenos de disco.",
    stock: 20,
  },
  {
    name: "Mesa Plegable",
    price: 59.99,
    category: "Muebles",
    description: "Mesa plegable compacta ideal para espacios reducidos.",
    stock: 50,
  },
  {
    name: "Sudadera con Capucha",
    price: 29.99,
    category: "Ropa",
    description: "Sudadera cómoda y abrigada con capucha ajustable.",
    stock: 120,
  },
  {
    name: "Cargador Inalámbrico",
    price: 19.99,
    category: "Accesorios",
    description: "Cargador inalámbrico compatible con múltiples dispositivos.",
    stock: 140,
  },
  {
    name: "Máquina de Coser",
    price: 89.99,
    category: "Electrodomésticos",
    description: "Máquina de coser portátil con 12 puntadas diferentes.",
    stock: 35,
  },
  {
    name: "Kit de Pesas Ajustables",
    price: 99.99,
    category: "Deportes",
    description: "Kit de pesas ajustables ideal para entrenamientos en casa.",
    stock: 55,
  },
  {
    name: "Plancha de Vapor",
    price: 24.99,
    category: "Electrodomésticos",
    description: "Plancha de vapor con ajuste de temperatura y rociador.",
    stock: 85,
  },
  {
    name: "Set de Cubiertos de Acero Inoxidable",
    price: 29.99,
    category: "Hogar",
    description:
      "Set de cubiertos para 6 personas, fabricados en acero inoxidable.",
    stock: 70,
  },
  {
    name: "Bolso Tote de Cuero",
    price: 49.99,
    category: "Moda",
    description: "Bolso tote de cuero con compartimento para laptop.",
    stock: 40,
  },
  {
    name: "Guitarra Acústica",
    price: 149.99,
    category: "Música",
    description:
      "Guitarra acústica de 6 cuerdas con acabado de madera natural.",
    stock: 25,
  },
  {
    name: "Monitor de 24 Pulgadas",
    price: 129.99,
    category: "Electrónica",
    description: "Monitor LED de 24 pulgadas con resolución Full HD.",
    stock: 30,
  },
  {
    name: "Aspiradora Robot",
    price: 179.99,
    category: "Electrodomésticos",
    description:
      "Aspiradora robot con programación automática y control remoto.",
    stock: 20,
  },
  {
    name: "Pulsera Fitness",
    price: 29.99,
    category: "Accesorios",
    description:
      "Pulsera de actividad física con monitor de frecuencia cardíaca.",
    stock: 95,
  },
  {
    name: "Set de Ollas de Cocina",
    price: 89.99,
    category: "Hogar",
    description: "Set de 10 piezas de ollas y sartenes antiadherentes.",
    stock: 60,
  },
];
